### PR TITLE
Redesign locale switcher

### PR DESCRIPTION
**Pull request by wrightmartin**

### CODE REVIEW

**Comment by garethrees** [comment]
I just get this:

screen shot 2015-08-04 at 12 55 06

I'm assuming I'm looking for one that looks the same as on WDTK?

**Comment by wrightmartin** [comment]
@garethrees 
screen shot 2015-08-04 at 14 22 03

That's what I get, Alaveteli core on 'develop'

**Comment by wrightmartin** [comment]
> Wonder whether the locale switcher should have assets/stylesheets/responsive/_locale_switcher.css.scss and get included in custom.css.scss?

Can you elaborate on this for me?

**Comment by garethrees** [comment]
>> Wonder whether the locale switcher should have assets/stylesheets/responsive/_locale_switcher.css.scss and get included in custom.css.scss?

>Can you elaborate on this for me?

So if you put all the locale switcher styles in `assets/stylesheets/responsive/_locale_switcher.css.scss` and then in `custom.css.scss` have `@import "_locale_switcher";`, like we do for `_utils` here: https://github.com/mysociety/alaveteli/blob/develop/app/assets/stylesheets/responsive/all.scss#L10-L11

**Comment by garethrees** [comment]
FWIW I'm not that attached to the idea, but it would isolate that piece of CSS as I can't imagine people are going to want to change it that often

**Pull request merged**
