### PR TITLE
Include pictorial element in logo, and improve size on mobiles

### PR DESCRIPTION
**Pull request by zarino**
Part of mysociety/alaveteli#2699.

Adding an icon to the logo makes it clear that it should be replaced when you customise the theme.

screen shot 2015-10-23 at 11 42 14

screen shot 2015-10-23 at 11 41 54

### CODE REVIEW

**Comment by garethrees** [comment]
This completely overlaps the locale switcher for me:

screen shot 2015-10-26 at 17 02 27

**Comment by garethrees** [comment]
Mobile version looks good :+1:

**Comment by garethrees** [comment]
Ah so the overlapping is caused because of the new, bigger core logo https://github.com/mysociety/alaveteli/pull/2866 – Guess we want to make it a bit smaller here :)

**Comment by zarino** [comment]
@garethrees – Fixed! The language switcher’s `left:` position is now based on the `$logo-width` variable so it shouldn’t overlap any more. https://github.com/mysociety/alavetelitheme/commit/6713c872254cb9ee55b73ba16c5bd8f16432da76

**Comment by garethrees** [comment]
Looks good! :+1:

**Comment by davewhiteland** [comment]
@zarino thanks for this (as it was me who kicked off the original put-a-graphic-in-there issue :-) ), nicely done

**Pull request merged**
