### PR TITLE
Change colour scheme

### PR DESCRIPTION
**Pull request by wrightmartin**
This updates the colour scheme of alaveteli theme to one similar to alaveteli.org

It also greatly simplifies the way colours are used and customised by theme users

screen shot 2015-08-18 at 15 58 24

### CODE REVIEW

**Comment by garethrees** [comment]
Would be great to dim the colour of the sidebar text as per alaveteli.org

**Comment by garethrees** [comment]
Looking really good. Few tweaks and comments but starting to come together nicely! :cake:

**Comment by wrightmartin** [comment]
Thanks for the feedback @garethrees - I've pushed an updated version with these changes, here's what it looks like now

screen shot 2015-08-20 at 11 52 22

**Comment by garethrees** [comment]
Cheers! :tada:

**Pull request merged**
